import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Background from "@/components/globalbackground/Background";
import Header from "@/components/Header/Header";
import Storeprovider from "@/lib/reduxtoolkit/store/Storeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="false" className={inter.className}>
        <Storeprovider>
        <div className="relative z-50 bg-transparent">
          <Header />
          {children}
        </div>
        <Background />
        </Storeprovider>
      </body>
    </html>
  );
}
